In [17]:
import pandas as pd
import numpy as np
from numpy.linalg import svd

# Tarining Data

In [85]:
X = np.random.rand(100,3)
X.shape # 3d Data

(100, 3)

# Centering Data

In [80]:
X_centered = X - X.mean()

# Calculating SVD

In [81]:
U,s,Vt = svd(X_centered)

### Principal Components

In [97]:
c1 = Vt.T[:,0]
c2 = Vt.T[:,1]
c3 = Vt.T[:,2]

# PC's

In [92]:
c1

array([-0.71846808,  0.35323035, -0.59919274])

----

# Projecting on lower Dimension

In [88]:
# Projecting to the 2D space

In [98]:
w2 = Vt.T[:, :2] # first two PC's FOR 2d PROJECTION
w2

array([[-0.71846808, -0.1283408 ],
       [ 0.35323035, -0.91398511],
       [-0.59919274, -0.38491539]])

In [100]:
X2d = X_centered.dot(w2)

In [101]:
X2d

array([[ 5.70209378e-02, -2.34110548e-01],
       [ 1.98126917e-01,  3.02274512e-01],
       [-4.95794467e-01,  2.27507024e-01],
       [ 1.55760250e-03, -5.91396132e-01],
       [ 9.06288607e-02,  7.83641867e-02],
       [-8.44836533e-02,  6.03659329e-02],
       [-3.22159250e-01,  3.96709517e-01],
       [ 4.44817996e-02, -5.16869208e-01],
       [ 1.40950387e-01,  6.29257999e-02],
       [-1.67789940e-01, -3.97676612e-01],
       [ 5.23195966e-02,  4.91060843e-02],
       [-5.39244889e-04, -1.39262574e-01],
       [-5.42617525e-02, -3.80510612e-01],
       [-2.35626328e-01, -1.62103664e-01],
       [ 1.13429472e-01, -2.53370089e-01],
       [ 1.47025529e-02, -1.27600831e-02],
       [-2.09734307e-01, -3.28182387e-01],
       [ 5.54920230e-01,  1.70298263e-01],
       [ 3.48184978e-01, -3.82407430e-02],
       [ 3.29232609e-01,  2.99727982e-01],
       [-1.64693171e-01, -3.40399442e-01],
       [ 2.25667139e-01,  4.99378672e-01],
       [ 3.33795652e-01, -2.92045391e-01],
       [-6.