

# Decision Tree

You will be explore publicly available data from [LendingClub.com](www.lendingclub.com). Lending Club connects people who need money (borrowers) with people who have money (investors). Hopefully, as an investor you would want to invest in people who showed a profile of having a high probability of paying you back. You will try to create a model that will help predict this.

Lending club had a [very interesting year in 2016](https://en.wikipedia.org/wiki/Lending_Club#2016), so let's check out some of their data and keep the context in mind. This data is from before they even went public.

You will use lending data from 2007-2010 and be trying to classify and predict whether or not the borrower paid back their loan in full. You can  just use the csv already provided. It's recommended you use the csv provided as it has been cleaned of NA values.

Here are what the columns represent:
* credit.policy: 1 if the customer meets the credit underwriting criteria of LendingClub.com, and 0 otherwise.
* purpose: The purpose of the loan (takes values "credit_card", "debt_consolidation", "educational", "major_purchase", "small_business", and "all_other").
* int.rate: The interest rate of the loan, as a proportion (a rate of 11% would be stored as 0.11). Borrowers judged by LendingClub.com to be more risky are assigned higher interest rates.
* installment: The monthly installments owed by the borrower if the loan is funded.
* log.annual.inc: The natural log of the self-reported annual income of the borrower.
* dti: The debt-to-income ratio of the borrower (amount of debt divided by annual income).
* fico: The FICO credit score of the borrower.
* days.with.cr.line: The number of days the borrower has had a credit line.
* revol.bal: The borrower's revolving balance (amount unpaid at the end of the credit card billing cycle).
* revol.util: The borrower's revolving line utilization rate (the amount of the credit line used relative to total credit available).
* inq.last.6mths: The borrower's number of inquiries by creditors in the last 6 months.
* delinq.2yrs: The number of times the borrower had been 30+ days past due on a payment in the past 2 years.
* pub.rec: The borrower's number of derogatory public records (bankruptcy filings, tax liens, or judgments).

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline

In [2]:
data = pd.read_csv("loan_data.csv")
data.head()

credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   
4              1         credit_card    0.1426       102.92       11.299732   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1               0   
1  14.29   707        2760.000000      33623        76.7               0   
2  11.63   682        4710.000000       3511        25.6               1   
3   8.10   712        2699.958333      33667        73.2               1   
4  14.97   667        4066.000000       4740        39.5               0   

   delinq.2yrs  pub.rec  not.fully.paid  
0            0        0               0  
1            0        0               0  
2            0        0               0  
3            0        0               0  
4            1        0               0

In [3]:
data.describe(include='all')

credit.policy             purpose     int.rate  installment  \
count     9578.000000                9578  9578.000000  9578.000000   
unique            NaN                   7          NaN          NaN   
top               NaN  debt_consolidation          NaN          NaN   
freq              NaN                3957          NaN          NaN   
mean         0.804970                 NaN     0.122640   319.089413   
std          0.396245                 NaN     0.026847   207.071301   
min          0.000000                 NaN     0.060000    15.670000   
25%          1.000000                 NaN     0.103900   163.770000   
50%          1.000000                 NaN     0.122100   268.950000   
75%          1.000000                 NaN     0.140700   432.762500   
max          1.000000                 NaN     0.216400   940.140000   

        log.annual.inc          dti         fico  days.with.cr.line  \
count      9578.000000  9578.000000  9578.000000        9578.000000   
unique             NaN          NaN          NaN                NaN   
top                NaN          NaN          NaN                NaN   
freq               NaN          NaN          NaN                NaN   
mean         10.932117    12.606679   710.846314        4560.767197   
std           0.614813     6.883970    37.970537        2496.930377   
min           7.547502     0.000000   612.000000         178.958333   
25%          10.558414     7.212500   682.000000        2820.000000   
50%          10.928884    12.665000   707.000000        4139.958333   
75%          11.291293    17.950000   737.000000        5730.000000   
max          14.528354    29.960000   827.000000       17639.958330   

           revol.bal   revol.util  inq.last.6mths  delinq.2yrs      pub.rec  \
count   9.578000e+03  9578.000000     9578.000000  9578.000000  9578.000000   
unique           NaN          NaN             NaN          NaN          NaN   
top              NaN          NaN             NaN          NaN          NaN   
freq             NaN          NaN             NaN          NaN          NaN   
mean    1.691396e+04    46.799236        1.577469     0.163708     0.062122   
std     3.375619e+04    29.014417        2.200245     0.546215     0.262126   
min     0.000000e+00     0.000000        0.000000     0.000000     0.000000   
25%     3.187000e+03    22.600000        0.000000     0.000000     0.000000   
50%     8.596000e+03    46.300000        1.000000     0.000000     0.000000   
75%     1.824950e+04    70.900000        2.000000     0.000000     0.000000   
max     1.207359e+06   119.000000       33.000000    13.000000     5.000000   

        not.fully.paid  
count      9578.000000  
unique             NaN  
top                NaN  
freq               NaN  
mean          0.160054  
std           0.366676  
min           0.000000  
25%           0.000000  
50%           0.000000  
75%           0.000000  
max           1.000000

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 14 columns):
credit.policy        9578 non-null int64
purpose              9578 non-null object
int.rate             9578 non-null float64
installment          9578 non-null float64
log.annual.inc       9578 non-null float64
dti                  9578 non-null float64
fico                 9578 non-null int64
days.with.cr.line    9578 non-null float64
revol.bal            9578 non-null int64
revol.util           9578 non-null float64
inq.last.6mths       9578 non-null int64
delinq.2yrs          9578 non-null int64
pub.rec              9578 non-null int64
not.fully.paid       9578 non-null int64
dtypes: float64(6), int64(7), object(1)
memory usage: 1.0+ MB


In [5]:
data['not.fully.paid'].value_counts()

0    8045
1    1533
Name: not.fully.paid, dtype: int64

In [6]:
data['purpose'].value_counts()

debt_consolidation    3957
all_other             2331
credit_card           1262
home_improvement       629
small_business         619
major_purchase         437
educational            343
Name: purpose, dtype: int64

In [7]:
X = data.drop('not.fully.paid', axis=1)
y = data['not.fully.paid']

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    stratify=y, 
                                                    test_size=0.25)

In [9]:
X_train.head()

credit.policy             purpose  int.rate  installment  \
3012              1         credit_card    0.0963       481.42   
8099              0  debt_consolidation    0.1741       622.13   
1760              1           all_other    0.0932       159.74   
147               1           all_other    0.0807       259.58   
40                1    home_improvement    0.0807       156.84   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
3012       10.666627  10.49   777        6329.958333       4963        15.8   
8099       10.819778  16.92   647        5490.000000       4693        28.8   
1760       10.819858   0.36   757        3210.000000         49         0.5   
147        10.799576   9.89   772        9870.000000       7744        17.1   
40         12.100712   5.55   742        4019.000000      40934        26.3   

      inq.last.6mths  delinq.2yrs  pub.rec  
3012               0            0        0  
8099               8            0        1  
1760               2            3        0  
147                0            0        0  
40                 0            0        0

In [10]:
y_train.head()

3012    0
8099    1
1760    0
147     0
40      0
Name: not.fully.paid, dtype: int64

In [11]:
X_train.columns

Index(['credit.policy', 'purpose', 'int.rate', 'installment', 'log.annual.inc',
       'dti', 'fico', 'days.with.cr.line', 'revol.bal', 'revol.util',
       'inq.last.6mths', 'delinq.2yrs', 'pub.rec'],
      dtype='object')

In [12]:
num_attribs = [ 'int.rate', 'installment', 'log.annual.inc',
       'dti', 'fico', 'days.with.cr.line', 'revol.bal', 'revol.util']

In [52]:
cat_attribs = ['credit.policy','purpose','inq.last.6mths','delinq.2yrs','pub.rec']

In [53]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([
        ('std_scaler', StandardScaler()),
    ])


In [54]:
from sklearn.preprocessing import OneHotEncoder
cat_encoder = OneHotEncoder()

from sklearn.compose import ColumnTransformer

full_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        ("cat", OneHotEncoder(), cat_attribs),
    ])

X_train_prepared = full_pipeline.fit_transform(X_train)

In [55]:
X_train_prepared

<7183x59 sparse matrix of type '<class 'numpy.float64'>'
	with 93379 stored elements in Compressed Sparse Row format>

In [56]:
from sklearn.tree import DecisionTreeClassifier

tree_classifer1 = DecisionTreeClassifier(random_state=42, max_depth=5)
tree_classifer1.fit(X_train_prepared, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=5, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=42, splitter='best')

In [57]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(tree_classifer1, X_train_prepared, y_train, scoring='neg_mean_squared_error', cv=3)
clf_1_rmse_scores = np.sqrt(-scores)
clf_1_rmse_scores

array([0.40918474, 0.40978018, 0.4247954 ])

In [58]:
sum(clf_1_rmse_scores)/3

# Lets say this is the best model

0.41458677274024863

# Testing

In [59]:
X_test_prepared = full_pipeline.fit_transform(X_test)

In [60]:
X_test_prepared 

<2395x48 sparse matrix of type '<class 'numpy.float64'>'
	with 31135 stored elements in Compressed Sparse Row format>

In [62]:
predicted = tree_classifer1.predict(X_train_prepared)
predicted

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

# Confusion Matrix

In [63]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_train, predicted)

array([[6010,   23],
       [1083,   67]], dtype=int64)

In [64]:
from sklearn.metrics import precision_score, recall_score

precision_score(y_train, predicted)

0.7444444444444445

In [65]:
recall_score(y_train, predicted)

0.058260869565217394